name: CI

on: [push]

jobs:
  # ============================================================================

  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    # --------------------------------------------------------------------------

    - name: init
      run: npm ci

    - name: test
      run: npm test

    # --------------------------------------------------------------------------

    env:
      GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
